### ISSUE TITLE
testcontainers-localstack missing `get_client`

### ISSUE THREAD

**Issue by bdgeise** [testcontainers/testcontainers-python#372]
**Describe the bug**
`testcontainers-localstack` not installing with most recent code base on `0.0.1rc1`

Installed `testcontainers` using `poetry add testcontainers` and added localstack `poetry add testcontainers-localstack`

`pyproject.toml` has versions
`testcontainers-localstack = "^0.0.1rc1"`
`testcontainers = "^3.7.1"`

`testcontainers-localstack` has the following entry in `poetry.lock`

```
[[package]]
name = "testcontainers-localstack"
version = "0.0.1rc1"
description = "LocalStack component of testcontainers-python."
optional = false
python-versions = ">=3.7"
files = [
    {file = "testcontainers_localstack-0.0.1rc1-py3-none-any.whl", hash = "sha256:c3b2d3e97511360a7d0a4115338415a9c25e4463877d4d155aad848e4227e755"},
]
```

**Runtime environment**

```bash
# Get the operating system information (on a unix os).
Darwin brandons-mbp.lan 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
# Get the python version.
Python 3.8.9
```

**Comment by alexanderankin** [comment]
4.0.0-rc2 was published yesterday, I haven't checked if this code is there but it should be I think

**Comment by alexanderankin** [comment]
#405

**Comment by covatic-john** [comment]
This still fails with 4.0.0 , needs release of the localstack component 
AttributeError: 'LocalStackContainer' object has no attribute 'get_client'

**Comment by alexanderankin** [comment]
We can't publish those as described in the pinned issue #412 so it's
"testcontainers[localstack]" again

**Comment by covatic-john** [comment]
Trying now :)

**Comment by covatic-john** [comment]
@alexanderankin this get_client working on 4.0.0 release.

**Comment by alexanderankin** [comment]
> @alexanderankin this get_client working on 4.0.0 release.

closing this!
